FROM mcr.microsoft.com/powershell:7
# Can be 'linux-x64', 'linux-arm64', 'linux-arm', 'rhel.6-x64'.
ENV TARGETARCH=linux-x64

WORKDIR /azp

COPY start.sh .
RUN chmod +x start.sh

ENTRYPOINT ["./start.sh"]
